export const TEST = 'DIRECT:TEST';
export const ON_MARKER_CLICK = 'DIRECT:ON_MARKER_CLICK';
export const ON_MAP_CLICK = 'DIRECT:ON_MAP_CLICK';
export const CLOSE_DIALOG = 'DIRECT:CLOSE_DIALOG';
export const CLOSE_CARD_DIALOG = 'DIRECT:CLOSE_CARD_DIALOG';
export const SET_MARKERS = 'DIRECT:SET_MARKERS';
export const ON_MARKER_CLOSE = 'DIRECT:ON_MARKER_CLOSE';
export const SHOW_MARKER_INFO = 'DIRECT:SHOW_MARKER_INFO';
